name: relative_routes
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router:
    git:
      url: https://github.com/ThangVuNguyenViet/packages.git
      path: packages/go_router

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder:
    git:
      url: https://github.com/ThangVuNguyenViet/packages.git
      path: packages/go_router_builder
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
